version: "3.8"
services:
  web_server: 
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      EXTERNAL_PROTOCOL: http
      EXTERNAL_PORT: 4000
      EXTERNAL_HOSTNAME: 4000
      SECRET_KEY_BASE: uCT5v2kh27BkmIAMtVmKXUgXX4e60GQO2lXn0nQPoy8Zb7EpL65I/l1oKHmXF1fD
    ports: 
      - "4000"
      - "4369"
      - "4370"
    networks:
      - web_server

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - web_server
    restart: always
    ports:
      - "4000:4000"
    networks:
      - web_server

networks:
  web_server: 
    name: web_server